import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "REXANTEC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es-419">
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
